[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cryogmm"
version = "0.1.0"
description = "Cryo-EM Gaussian Mixture Model"
authors = [
    { name="Minhuan Li", email="minhuanli@flatironinstitute.org" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
cryogmm-fps = "cryogmm.cli.fps_clustering:main"
cryogmm-reweight = "cryogmm.cli.reweighting:main"
cryogmm-build-gmm = "cryogmm.cli.gmm_build:main"

[project.urls]
Homepage = "https://github.com/minhuanli/cryogmm"

[tool.setuptools.packages.find]
include = ["cryogmm*"]

[tool.setuptools.package-dir]
"" = "."